# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        nim: ['== 2.0.0', '== 2.2.0']

    name: Nim ${{ matrix.nim }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nim-lang/setup-nimble-action@v1
        with:
          nimble-version: 'nightly'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pkgconfig
        if: runner.os == 'Windows'
        run: choco install pkgconfiglite
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
      - run: nimble --requires="nim ${{matrix.nim}}" buildExamples
