# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        nim: ['~= 2.0.0', '~= 2.2.0']
        qt: ['5.15', '6.4']

    name: CI ${{ matrix.os }}, Nim ${{ matrix.nim }} , Qt ${{matrix.qt}}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nim-lang/setup-nimble-action@v1
        with:
          nimble-version: 'nightly'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pkgconfig
        if: runner.os == 'Windows'
        run: choco install pkgconfiglite
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '${{matrix.qt}}.*'
      - name: Tests
        run: |
          echo $PKG_CONFIG_PATH
          nimble install https://github.com/seaqt/nim-seaqt.git@#qt-${{matrix.qt}}
          nimble --requires="nim ${{matrix.nim}}" --requires="https://github.com/seaqt/nim-seaqt.git#qt-${{matrix.qt}}" buildExamples
